"""Search models for orchestration and job management."""

from datetime import datetime, timezone, date
from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from vusca.models.calendar import PTOWindow
from vusca.models.flight import Itinerary


def now_utc() -> datetime:
    return datetime.now(timezone.utc)


class JobStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class SearchLegTask(BaseModel):
    """A unit of work: query flights from origin to destination on a given date."""
    task_id: str
    origin: str
    destination: str
    travel_date: date
    status: str = "PENDING"  # PENDING, SUCCESS, FAILED, CACHED
    results_count: int = 0
    min_price_eur: Optional[float] = None
    provider_name: Optional[str] = None
    elapsed_seconds: Optional[float] = None
    error_message: Optional[str] = None
    retries: int = 0


class SearchJob(BaseModel):
    """Tracks a full multi-city flight search mission, supporting pause and resume."""
    job_id: str
    origin: str
    final_destination: str
    status: JobStatus = JobStatus.PENDING
    created_at: datetime = Field(default_factory=now_utc)
    updated_at: datetime = Field(default_factory=now_utc)
    
    # User preferences
    country: str = "ES"
    subdivision: Optional[str] = "MD"
    max_pto_days: int = 5
    preferred_month: Optional[str] = None  # e.g. "2026-10"
    return_destinations: List[str] = Field(default_factory=list)
    min_stopover_days: int = 1
    max_stopover_days: int = 3
    
    # Candidate lists generated by Agents
    candidate_windows: List[PTOWindow] = Field(default_factory=list)
    candidate_stopovers: List[str] = Field(default_factory=list)
    stopover_names: Dict[str, str] = Field(default_factory=dict)
    
    # Execution tracking
    tasks: List[SearchLegTask] = Field(default_factory=list)
    completed_task_count: int = 0
    total_task_count: int = 0
    
    # Results
    itineraries: List[Itinerary] = Field(default_factory=list)
    ai_final_analysis: Optional[str] = None

    def update_progress(self):
        self.completed_task_count = sum(
            1 for t in self.tasks if t.status in ("SUCCESS", "CACHED", "FAILED")
        )
        self.total_task_count = len(self.tasks)
        self.updated_at = now_utc()
